### ISSUE TITLE
Jason Rowland/Code Review

### ISSUE THREAD

**Issue by jasonrowland86** [BStudies/MyAssistant#1]
Its hard to know what to say in a short amount of time: 

I was curious about this snippet:

 while(count < clothings.length){
        outfitString+=','+clothings[count].alt;
        ++count;
    }
What does the ',' do?

This is also cool: 

let postToDB = function(){
    //get clothings via checkbox
    let outfitString = getPostingString();
    let weatherObjectString = getweatherInfo();

    //make a post to /user
    fetch(`/user/${outfitString}&${weatherObjectString}`, {
        method: 'POST',
        credentials: 'include',
    })

Reading this function clarified my understanding of fetch, I thought it only retrieved data.
Sorry my feedback isn't much. I was having so many of my own issues that its still hard for me to read through and understand it all. Good organization though. 
Also the seedUsersData helper function is nice.

**Comment by BStudies** [comment]
Thanks Jason I appreciate the comments! 

For my 
```javascript
while(count < clothings.length){
outfitString+=','+clothings[count].alt;
++count;
}
```
The ',' is ment to build a string that looks like this:
"mens_jeans,mens_boots,mens_umbrella"

So I start with the string "mens_jeans"
then keep appending ",next_clothing" so later I can separate the string with a .split(',') method and get back an array from the string. 

😄
